name: alr build check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Setup Alire
        run: |
          curl -L -o alr.zip https://github.com/alire-project/alire/releases/download/v2.0.2/alr-2.0.2-bin-x86_64-linux.zip
          unzip alr.zip -d alire
          sudo mv alire/bin/alr /usr/local/bin/alr

      - name: Install Dependencies
        run: |
          export ALR_NONINTERACTIVE=1
          alr with

      - name: Build Project
        run: alr build
