name: Ada Build Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Alire Linux Binary
        run: |
          curl -L -o alr.zip https://github.com/alire-project/alire/releases/download/v2.0.2/alr-2.0.2-bin-x86_64-linux.zip
          unzip alr.zip -d alire
          sudo mv alire/bin/alr /usr/local/bin/alr

      - name: Set Non-Interactive Environment
        run: |
          export ALR_NONINTERACTIVE=1
          export ALR_TOOLCHAIN_AUTO=1  # Ensures toolchain is automatically selected

      - name: Install Project Dependencies
        run: |
          yes | alr with

      - name: Build Project
        run: |
          yes | alr build
