name: alr build check

on:
  push:
    paths:
      - 'src/**.adb'
      - 'src/**.ads'
      - 'src/**.gpr'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: alire-project/setup-alire@v2.21

      - name: Build
        run: >
          alr index --add git+https://github.com/PSU-Capstone-Team20/RINA_for_Space --name rina &&
          cd src && alr build

